version: '3'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - vmongo:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-dynamic
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    networks:
      - app-network

  db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:

volumes:
  vmongo: